// Biblioteca de documentos. O Edital e os Anexos I a VII foram aprovados
// pelo Comitê de Governança da AGU (CG-AGU) e seus arquivos PDF reais estão
// publicados em /public/documentos, disponíveis para visualização e download.
// Anexos VIII a XV são citados no edital (item 27.5) mas seu arquivo ainda
// não foi fornecido — permanecem como referência estrutural, indisponíveis.
//
// Anexo I é documento de referência (não é formulário) e também tem texto
// integral navegável em /documentos/anexo-i (ver anexo-i-texto.ts).

import type { Documento } from "@/types/content";

export const DOCUMENTOS: Documento[] = [
  {
    id: "edital-consolidado",
    numero: "Edital",
    titulo:
      "Edital de Chamamento Público Permanente para Habilitação Institucional de Fundações de Apoio",
    categoria: "Edital",
    finalidade:
      "Texto integral do chamamento público permanente para habilitação institucional de fundações de apoio interessadas em atuar junto à ICT-AGU.",
    obrigatorio: "informativo",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlVisualizar: "/edital/texto",
    urlDownloadPdf: "/documentos/edital-habilitacao-fundacoes-apoio.pdf",
  },
  {
    id: "anexo-i-areas-atividades",
    numero: "Anexo I",
    titulo: "Áreas e atividades passíveis de apoio",
    categoria: "Documentos de referência",
    finalidade:
      "Relação exemplificativa das áreas e atividades que poderão ser objeto de apoio pelas fundações habilitadas (pesquisa e desenvolvimento, transformação digital, IA, propriedade intelectual, capacitação, entre outras).",
    quandoUtilizar:
      "Para identificar as áreas de especialização a indicar no requerimento (Anexo II) e no Formulário de Capacidade Técnica (Anexo VI).",
    obrigatorio: "informativo",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlVisualizar: "/documentos/anexo-i",
    urlDownloadPdf: "/documentos/anexo-i-areas-atividades.pdf",
  },
  {
    id: "anexo-ii-requerimento",
    numero: "Anexo II",
    titulo: "Formulário de Requerimento de Habilitação Institucional",
    categoria: "Formulários",
    finalidade:
      "Formulário principal do pedido: identifica a fundação, o representante legal, a ICT de origem, o registro/credenciamento perante MEC e MCTI, a situação de autorização para atuar junto à ICT-AGU e o perfil institucional e áreas de atuação pretendidas.",
    quandoUtilizar: "No momento da apresentação do requerimento de habilitação.",
    obrigatorio: "obrigatorio",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-ii-formulario-requerimento.pdf",
  },
  {
    id: "anexo-iii-checklist-documental",
    numero: "Anexo III",
    titulo: "Lista de Verificação Documental",
    categoria: "Formulários",
    finalidade:
      "Checklist oficial que acompanha o requerimento, organizado por bloco (habilitação jurídica, registro/credenciamento, solidez financeira, governança e integridade, capacidade técnica e tecnológica, experiência anterior, proteção de dados e, em fase posterior, regularidade fiscal/Cadin).",
    quandoUtilizar: "Preenchido junto com o requerimento, para conferência da comissão.",
    obrigatorio: "obrigatorio",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-iii-checklist-documental.pdf",
  },
  {
    id: "anexo-iv-anuencia-ict-origem",
    numero: "Anexo IV",
    titulo: "Declaração de Anuência da ICT de Origem",
    categoria: "Declarações",
    finalidade:
      "Declaração pela qual a ICT à qual a fundação está originalmente vinculada manifesta anuência à sua participação no procedimento de habilitação junto à ICT-AGU.",
    quandoUtilizar: "Quando a fundação já possui vínculo institucional com outra ICT de origem.",
    obrigatorio: "condicional",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-iv-declaracao-ict-origem.pdf",
  },
  {
    id: "anexo-v-inexistencia-impedimentos",
    numero: "Anexo V",
    titulo: "Declaração de Inexistência de Impedimentos e de Compromisso com a Integridade",
    categoria: "Declarações",
    finalidade:
      "Declaração sobre a inexistência de impedimentos legais à participação e compromisso com integridade, prevenção de conflitos de interesses, relacionamento com agentes públicos e transparência.",
    quandoUtilizar: "Anexada ao requerimento de habilitação.",
    obrigatorio: "obrigatorio",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-v-declaracao-impedimentos.pdf",
  },
  {
    id: "anexo-vi-capacidade-tecnica",
    numero: "Anexo VI",
    titulo: "Formulário de Capacidade Técnica e Operacional",
    categoria: "Formulários",
    finalidade:
      "Formulário detalhado sobre estrutura física, quadro de pessoal, capacidade tecnológica, gestão de recursos, compras, bolsas, prestação de contas, captação de recursos, atuação territorial e proteção de dados da fundação.",
    quandoUtilizar: "Anexado ao requerimento de habilitação.",
    obrigatorio: "obrigatorio",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-vi-capacidade-tecnica.pdf",
  },
  {
    id: "anexo-vii-projetos-executados",
    numero: "Anexo VII",
    titulo: "Relação de Projetos Executados",
    categoria: "Formulários",
    finalidade:
      "Relação e detalhamento dos projetos executados ou em execução pela fundação nos últimos cinco anos, usada para comprovar experiência técnica e operacional.",
    quandoUtilizar: "Anexado ao requerimento, com foco nas experiências mais relevantes para a ICT-AGU.",
    obrigatorio: "obrigatorio",
    formatos: ["PDF"],
    versao: "Aprovada pelo CG-AGU",
    dataAtualizacao: "2026-09-03",
    disponivel: true,
    novo: true,
    urlDownloadPdf: "/documentos/anexo-vii-relacao-projetos.pdf",
  },
  {
    id: "anexo-viii-matriz-avaliacao",
    numero: "Anexo VIII",
    titulo: "Matriz de avaliação institucional",
    categoria: "Documentos de referência",
    finalidade: "Matriz utilizada pela comissão para avaliar a capacidade institucional da fundação.",
    obrigatorio: "informativo",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-ix-certificado-habilitacao",
    numero: "Anexo IX",
    titulo: "Certificado de habilitação",
    categoria: "Documentos de referência",
    finalidade: "Modelo do certificado emitido pela AGU à fundação incluída no Cadastro de Fundações de Apoio da ICT-AGU.",
    obrigatorio: "informativo",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-x-relatorio-anual",
    numero: "Anexo X",
    titulo: "Relatório anual",
    categoria: "Formulários",
    finalidade:
      "Formulário de atualização anual exigido das fundações habilitadas (relatório de gestão, desempenho, demonstrações contábeis e atos ministeriais atualizados).",
    quandoUtilizar: "Anualmente, após a habilitação, enquanto vigente o vínculo com a ICT-AGU.",
    obrigatorio: "condicional",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-xi-matriz-escolha-projeto",
    numero: "Anexo XI",
    titulo: "Matriz de escolha por projeto",
    categoria: "Documentos de referência",
    finalidade: "Matriz de critérios e pesos utilizada na seleção de fundação habilitada para programa ou projeto específico.",
    obrigatorio: "informativo",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-xii-proposta-tecnica",
    numero: "Anexo XII",
    titulo: "Proposta técnica e operacional",
    categoria: "Formulários",
    finalidade: "Formulário de proposta técnica e operacional apresentado pela fundação em processo de seleção para projeto específico.",
    quandoUtilizar: "Quando convocada para seleção específica de programa ou projeto.",
    obrigatorio: "condicional",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-xiii-protecao-dados",
    numero: "Anexo XIII",
    titulo: "Declaração de Proteção de Dados e Segurança da Informação",
    categoria: "Declarações",
    finalidade: "Declaração de compromisso da fundação com a legislação de proteção de dados e com as normas de segurança da informação da AGU.",
    quandoUtilizar: "Anexada ao requerimento de habilitação.",
    obrigatorio: "obrigatorio",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-xiv-termo-ciencia",
    numero: "Anexo XIV",
    titulo: "Termo de ciência e compromisso",
    categoria: "Declarações",
    finalidade: "Termo de ciência das condições do edital e de compromisso com sua integral observância.",
    obrigatorio: "informativo",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
  {
    id: "anexo-xv-cronograma",
    numero: "Anexo XV",
    titulo: "Cronograma",
    categoria: "Documentos de referência",
    finalidade:
      "Cronograma inicial do chamamento permanente, incluindo a organização dos ciclos trimestrais de análise instrutória.",
    obrigatorio: "informativo",
    formatos: ["A confirmar"],
    versao: "Documento a ser publicado",
    dataAtualizacao: null,
    disponivel: false,
  },
];

export function obterDocumentoPorId(id: string): Documento | undefined {
  return DOCUMENTOS.find((doc) => doc.id === id);
}

export const CATEGORIAS_DOCUMENTO = [
  "Edital",
  "Anexos",
  "Formulários",
  "Declarações",
  "Modelos",
  "Guias e orientações",
  "Comunicados",
  "Retificações",
  "Resultados",
  "Documentos de referência",
] as const;
