import type { EtapaJornada } from "@/types/content";

// Etapas reconstituídas a partir do fluxo real descrito nas Seções 8 a 18
// da minuta do edital: apresentação do requerimento, conferência e análise
// pela comissão multi-institucional, eventual diligência, resultado
// preliminar, recurso, deliberação do CG-AGU e inclusão no Cadastro de
// Fundações de Apoio da ICT-AGU, com vigência de até 5 anos e atualização
// anual.

export const ETAPAS_JORNADA: EtapaJornada[] = [
  {
    id: "leitura-edital",
    ordem: 1,
    nome: "Leitura do edital",
    objetivo: "Compreender o objeto, as regras, os impedimentos e os requisitos da habilitação institucional.",
    providenciaEsperada: "Ler o edital de chamamento público permanente e seus anexos na íntegra, com atenção às Seções 6 e 7 (condições de participação e impedimentos).",
    documentosRelacionados: ["edital-consolidado", "anexo-i-areas-atividades"],
    prazo: "Sem prazo — o chamamento é permanente.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Entendimento claro sobre o objeto, os efeitos e os limites da habilitação institucional.",
    cuidados: [
      "A habilitação não gera direito subjetivo à contratação nem assegura exclusividade ou volume mínimo de projetos.",
      "Verificar se está consultando a versão mais atual da minuta/edital antes de prosseguir.",
    ],
    linkRelacionado: { label: "Consultar o edital", href: "/edital" },
  },
  {
    id: "verificacao-requisitos",
    ordem: 2,
    nome: "Verificação dos requisitos e impedimentos",
    objetivo: "Confirmar se a fundação atende às condições de participação (Seção 6) e não incorre em nenhum impedimento (Seção 7).",
    providenciaEsperada: "Conferir registro e credenciamento vigentes perante o MEC e o MCTI, anuência da ICT de origem (quando aplicável) e ausência das hipóteses de impedimento listadas no edital.",
    documentosRelacionados: [],
    prazo: "Sem prazo — o chamamento é permanente.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Confirmação de elegibilidade para apresentar o requerimento de habilitação.",
    cuidados: ["A regularidade fiscal, trabalhista e perante o Cadin não é exigida nesta fase — apenas no pedido de autorização, conforme item 9.10."],
    linkRelacionado: { label: "Ver requisitos no checklist", href: "/checklist" },
  },
  {
    id: "organizacao-documentacao",
    ordem: 3,
    nome: "Organização da documentação",
    objetivo: "Reunir os documentos de habilitação jurídica e institucional, solidez financeira, governança/integridade, capacidade técnica/tecnológica e experiência anterior (Seção 9).",
    providenciaEsperada: "Levantar estatuto, atas, CNPJ, demonstrações financeiras, políticas de integridade e evidências de capacidade técnica e tecnológica.",
    documentosRelacionados: ["anexo-iii-checklist-documental"],
    prazo: "Sem prazo — o chamamento é permanente.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Documentação organizada e pronta para conferência, seguindo a ordem do Anexo III.",
    cuidados: ["Atenção a prazos de validade de certidões e à necessidade de assinatura eletrônica dos documentos exigíveis."],
    linkRelacionado: { label: "Usar o checklist de preparação", href: "/checklist" },
  },
  {
    id: "preenchimento-formularios",
    ordem: 4,
    nome: "Preenchimento dos formulários e declarações",
    objetivo: "Preencher corretamente o requerimento e os anexos que o instruem (Anexos II a VII).",
    providenciaEsperada: "Preencher o Formulário de Requerimento (Anexo II), a Lista de Verificação Documental (Anexo III), a Declaração de Anuência da ICT de Origem (Anexo IV, quando aplicável), a Declaração de Inexistência de Impedimentos (Anexo V), o Formulário de Capacidade Técnica e Operacional (Anexo VI) e a Relação de Projetos Executados (Anexo VII).",
    documentosRelacionados: [
      "anexo-ii-requerimento",
      "anexo-iii-checklist-documental",
      "anexo-iv-anuencia-ict-origem",
      "anexo-v-inexistencia-impedimentos",
      "anexo-vi-capacidade-tecnica",
      "anexo-vii-projetos-executados",
    ],
    prazo: "Sem prazo — o chamamento é permanente.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Formulários preenchidos, assinados eletronicamente e revisados.",
    cuidados: ["Utilizar sempre a versão mais recente dos formulários, quando publicados oficialmente."],
    linkRelacionado: { label: "Ver documentos e anexos", href: "/documentos" },
  },
  {
    id: "apresentacao-requerimento",
    ordem: 5,
    nome: "Apresentação do requerimento",
    objetivo: "Protocolar formalmente o requerimento de habilitação institucional, a qualquer tempo.",
    providenciaEsperada: "Encaminhar o requerimento e a documentação pelo canal oficial de protocolo, a ser definido pela AGU.",
    documentosRelacionados: [],
    prazo: "Recebimento contínuo e ininterrupto — sem data de encerramento.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Requerimento protocolado e autuado em processo administrativo próprio.",
    cuidados: ["O canal oficial de protocolo (ex.: SAPIENS ou protocolo digital) ainda será definido e divulgado pela AGU."],
    linkRelacionado: { label: "Canais de atendimento", href: "/atendimento" },
  },
  {
    id: "conferencia-analise",
    ordem: 6,
    nome: "Conferência e análise pela comissão",
    objetivo: "Verificação da documentação e avaliação da capacidade jurídica, técnica, financeira, tecnológica e institucional da fundação.",
    providenciaEsperada: "Aguardar a análise; a comissão multi-institucional (coordenada pelo LABORI) pode organizar a apreciação em ciclos trimestrais de natureza instrutória.",
    documentosRelacionados: [],
    prazo: "Ciclos trimestrais de natureza instrutória, sem prejuízo do recebimento contínuo de requerimentos.",
    responsavel: "Comissão de avaliação / NIT-AGU",
    resultadoEsperado: "Relatório técnico da comissão, com proposta de perfil institucional e recomendação de deferimento, deferimento condicionado ou indeferimento.",
    cuidados: [],
  },
  {
    id: "diligencias",
    ordem: 7,
    nome: "Eventual diligência",
    objetivo: "Esclarecer informações, corrigir falhas formais ou confirmar capacidades, quando solicitado pela comissão.",
    providenciaEsperada: "Responder à diligência dentro do prazo de 10 (dez) dias úteis, prorrogável mediante justificativa aceita pela comissão.",
    documentosRelacionados: [],
    prazo: "10 dias úteis, contados da notificação (prorrogáveis).",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Pendências sanadas dentro do prazo.",
    cuidados: ["A diligência não pode ser usada para criar condição material que não existia na data do requerimento.", "A ausência de resposta pode resultar em arquivamento ou indeferimento do pedido."],
  },
  {
    id: "resultado-preliminar",
    ordem: 8,
    nome: "Resultado preliminar",
    objetivo: "Publicação da decisão proposta pela comissão, com síntese dos fundamentos e eventuais condicionantes.",
    providenciaEsperada: "Acompanhar a publicação do resultado preliminar no sítio eletrônico da AGU.",
    documentosRelacionados: [],
    prazo: null,
    responsavel: "Comissão de avaliação",
    resultadoEsperado: "Resultado preliminar divulgado, com abertura de prazo recursal.",
    cuidados: [],
  },
  {
    id: "recurso",
    ordem: 9,
    nome: "Recurso, quando cabível",
    objetivo: "Permitir contestação fundamentada do resultado preliminar.",
    providenciaEsperada: "Apresentar recurso no prazo de 10 (dez) dias úteis, sem efeito suspensivo, dirigido à autoridade ou instância indicada no resultado.",
    documentosRelacionados: [],
    prazo: "10 dias úteis, contados da publicação do resultado preliminar.",
    responsavel: "Fundação interessada",
    resultadoEsperado: "Recurso analisado pela comissão (reconsideração) e, se mantido, encaminhado ao CG-AGU.",
    cuidados: ["Recursos intempestivos, sem fundamentação ou apresentados por pessoa sem poderes não serão conhecidos.", "O recurso não assegura habilitação provisória."],
  },
  {
    id: "decisao-cg-agu",
    ordem: 10,
    nome: "Deliberação do CG-AGU e resultado definitivo",
    objetivo: "Decisão final sobre o pedido de habilitação pelo Comitê de Governança da AGU.",
    providenciaEsperada: "Acompanhar a publicação do resultado definitivo no sítio eletrônico da AGU.",
    documentosRelacionados: [],
    prazo: null,
    responsavel: "Comitê de Governança da AGU (CG-AGU)",
    resultadoEsperado: "Deferimento, deferimento com condicionantes, restrição de perfil, sobrestamento ou indeferimento, sempre motivado e registrado em ata.",
    cuidados: ["A deliberação favorável não autoriza, isoladamente, o início de atividades quando ainda for necessária autorização ministerial (MEC/MCTI)."],
  },
  {
    id: "cadastro-vigencia",
    ordem: 11,
    nome: "Inclusão no Cadastro e vigência",
    objetivo: "Formalizar a habilitação e orientar a atuação futura junto à ICT-AGU.",
    providenciaEsperada: "A fundação habilitada é incluída no Cadastro de Fundações de Apoio da ICT-AGU (certificado conforme Anexo IX), com vigência de até 5 anos e atualização anual obrigatória (Anexo X).",
    documentosRelacionados: [],
    prazo: "Vigência de até 5 anos; atualização anual.",
    responsavel: "ICT-AGU e fundação habilitada",
    resultadoEsperado: "Fundação apta a ser considerada para seleção em programas e projetos específicos, mediante instrumentos jurídicos próprios.",
    cuidados: ["A habilitação institucional não representa contratação automática nem seleção para projeto determinado."],
    linkRelacionado: { label: "Após a habilitação", href: "/pos-credenciamento" },
  },
];
